### ISSUE TITLE
invalid literal for int when parsing message

### ISSUE THREAD

**Issue by tve** [dcspy/dcpmessage#1]
Hi, thanks so much for this lib, avoiding OpenDCS: yay!
I'm hitting an error trying to retrieve data:
```
[DEBUG] 2024-12-06T10:29:54PST  ./ingest-noaa-dcs/dcspy/dcspy/ldds_client.py]      [151]   "Authenticated user: MOTUS"
[DEBUG] 2024-12-06T10:29:54PST  ./ingest-noaa-dcs/dcspy/dcspy/search_criteria.py]  [124]   "#
# LRGS Search Criteria
#
DRS_SINCE: now - 1 day
DRS_UNTIL: now
DCP_ADDRESS: 33A1431E
"
[DEBUG] 2024-12-06T10:29:54PST  [/./ingest-noaa-dcs/dcspy/dcspy/ldds_client.py]      [190]   "Sending criteria message (filesize = 87 bytes)"
[DEBUG] 2024-12-06T10:29:54PST  [/./ingest-noaa-dcs/dcspy/dcspy/ldds_client.py]      [194]   "FAF0g00008Success"
[INFO]  2024-12-06T10:29:54PST  [/./ingest-noaa-dcs/dcspy/dcspy/ldds_client.py]      [217]   "Specified 'until' time reached"
Traceback (most recent call last):
  File "/./ingest-noaa-dcs/dcspy/main.py", line 17, in <module>
    messages = DcpMessage.get(username=credentials["username"],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./ingest-noaa-dcs/dcspy/dcspy/dcp_message.py", line 81, in get
    dcp_messages = DcpMessage.explode(dcp_block)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/./ingest-noaa-dcs/dcspy/dcspy/dcp_message.py", line 102, in explode
    message_length = int(message[start + DcpMessage.data_length:start + DcpMessage.header_length])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0n000'
```
Any suggestions?

**Comment by tve** [comment]
Looks like the issue is a misunderstand that `socket.read` in "blocking mode" somehow waits for all the data the server is going to send. It doesn't. The buffer size is a max amount and it's not set to the expected message length. I'll fix that...

Example of the issue. A 'n' request is sent, the server responds with a 9042 byte response, the socket.read provides the first 1024 (1014 data bytes after the header). Then request_dcp_block incorrectly asks for another block instead of finishing to read the 9042 bytes.

```
[DEBUG] 2024-12-06T11:29:48PST  [/home/tve/Projects/Motus/ingest-noaa-dcs/dcspy/dcspy/ldds_client.py]      [166]   "Requesting n"                                                                     
[DEBUG] 2024-12-06T11:29:48PST  [/home/tve/Projects/Motus/ingest-noaa-dcs/dcspy/dcspy/ldds_message.py]     [113]   "LddsMessage(n, 9042, 1014, b'33A1431E24341153640G33+0HN307EUP00031"\nC,1732099471.679,-1,0\n13.49\n 33A1431E24341153040G33-0NN307EUB00031"\nC,1732099112.197,-1,0\n13.47\n 33A1431E24
341152440G33-0NN307EUP00031"\nC,1732098751.473,-1,0\n13.41\n 33A1431E24341151840G33-0HN307EUP00031"
\nC,1732098391.916,-1,0\n13.36\n 33A1431E24341151240G34-0HN307EN200031"\nC,1732098032.345,-1,0\n13.
34\n 33A1431E24341150640G33-0HN307EUP00031"\nC,1732097671.907,-1,0\n13.29\n 33A1431E24341150040G33+
0HN307EUP00031"\nC,1732097312.423,-1,0\n13.27\n 33A1431E24341145440G33+0HN307EUP00031"\nC,173209695
2.943,-1,0\n13.24\n 33A1431E24341144840G34+0NN307EUB00031"\nC,1732096592.178,-1,0\n13.20\n 33A1431E
24341144240G34-0HN307EN200030"\nC,1732096232.76,-1,0\n13.16\n 33A1431E24341143640G33+0HN307EUP00031
"\nC,1732095873.211,-1,0\n13.16\n 33A1431E24341143040G34-0HN307EN100031"\nC,1732095512.733,-1,0\n13
.12\n 33A1431E24341142440G34+0NN307EUB00031"\nC,1732095153.275,-1,0\n13.13\n 33A1431E24341141840G33
+0NN307EUP00031"\nC,1732094792.438,-1,0\n13.05\n 33A1431E24341141240G34+0NN307EUP00031"\nC,17320944
32.957,-1,0\n12', b'FAF0n09042')"
[DEBUG] 2024-12-06T11:29:48PST  [/home/tve/Projects/Motus/ingest-noaa-dcs/dcspy/dcspy/ldds_client.py]      [166]   "Requesting n"
[DEBUG] 2024-12-06T11:29:48PST  [/home/tve/Projects/Motus/ingest-noaa-dcs/dcspy/dcspy/ldds_message.py]     [113]   "LddsMessage(None, 344, 344, b'.88\n 33A1431E24341140640G33+0NN307EUB00031"\nC,1732
094073.442,-1,0\n12.70\n 33A1431E24341140040G34-0NN307EN100031"\nC,1732093712.973,-1,0\n12.50\n 33A
1431E24341135440G34+0NN307EUP00049"\nNo messages available for transmission!\n12.30\n 33A1431E24341
134840G33+0NN307EUP00031"\nC,1732092993.725,-1,0\n12.18\n 33A1431E24341134240G33-0HN307EUP00031"\nC,17320926', None)"
```

**Comment by darshanbaralvw** [comment]
Would you be able to post your [search criteria](https://github.com/dcspy/dcspy?tab=readme-ov-file#search-criteria)?

**Comment by tve** [comment]
Sure: 
```
{"DRS_SINCE": "now - 1 day", "DRS_UNTIL": "now", "DCP_ADDRESS": [ "33A1431E" ]}
```
